### ISSUE TITLE
Allow Site-Configuration using the bot.properties

### ISSUE THREAD

**Issue by Vogel612** [Unihedro/JavaBot#58]
Currently the only way to change the chatserver is getting your hands dirty and editing the code available in the main-method.

This shouldn't be so hard and static. The used Domain should be configurable using the properties file (and have a reasonable default)

**Comment by Unihedro** [comment]
yes

**Comment by ByteCommander** [comment]
Good idea. I already missed this, being used to run the Python SE-ChatBot by ProgramFOX...
